---
parameters:
  registryDomain: '%env(REGISTRY_DOMAIN)%'

services:
  App\Infrastructure\Id2\ID2ServiceInterface:
    class: App\Infrastructure\Id2\DummyID2Service
  App\Infrastructure\HttpClients\Id2\Id2Client:
    class: App\Infrastructure\HttpClients\Id2\Id2ClientDummy
  App\Infrastructure\HttpClients\Id2\Id2ProductsClient:
    class: App\Infrastructure\HttpClients\Id2\Id2ProductsClientDummy
  App\Domain\Entity\SpecialistDocument\SpecialistDocument:
    class: App\Domain\Entity\SpecialistDocument\SpecialistDocument
  App\Infrastructure\HttpClients\Skills\SkillsClientInterface:
    class: App\Infrastructure\HttpClients\Skills\SkillsClientDummy
  Redis:
    class: Redis

  App\Infrastructure\HttpClients\SchoolProgram\SchoolProgramClientInterface:
    class: App\Infrastructure\HttpClients\SchoolProgram\SchoolProgramClient
    arguments:
      $apiUrl: '%env(SCHOOL_DATA_PROVIDER_SERVICE_URL)%'
      $defaultRequestTimeout: '%env(DEFAULT_REQUEST_TIMEOUT)%'

  App\Infrastructure\HttpClients\CrmApi\CrmApiClient:
    arguments:
      $logger: '@logger'
      $baseUrl: '%env(CRM_BASE_URL)%'
      $appId: '%env(CRM_APP_ID)%'
      $secretKey: '%env(CRM_SECRET_KEY)%'
      $defaultRequestTimeout: '%env(DEFAULT_REQUEST_TIMEOUT)%'
