---
parameters:
  logger.additional_fields:
    x-host: 'x-host'
services:
  "logger":
    class: Action\Logger\ActionLogger
    arguments:
      $level: 'warning'
      $configuration: null
      $additionalFields: '%logger.additional_fields%'
