---
easy_admin:
  entities:
    CustomValue:
      class: App\Domain\Entity\Event\CustomValue
      label: 'Кастомные свойства'
      list:
        item_permission: 'ROLE_MARKETER'
        actions:
          - show
          - {name: 'edit', template: 'easy_admin_role_supervisor.twig'}
        fields:
          - {property: 'id'}
          - {property: 'name', label: 'Название'}
          - {property: 'key', label: 'Key'}
          - {property: 'value', label: 'Value'}
      show:
        item_permission: 'ROLE_MARKETER'
        actions:
          - {name: 'edit', template: 'easy_admin_role_supervisor.twig'}
        fields:
          - {property: 'id'}
          - {property: 'name', label: 'Название'}
          - {property: 'key', label: 'Key'}
          - {property: 'value', label: 'Value'}
      edit:
        item_permission: ['ROLE_ADMIN', 'ROLE_SUPERVISOR']
        fields:
          - {property: 'id', type_options: {disabled: true}}
          - {property: 'name', label: 'Название', type_options: {disabled: true}}
          - {property: 'key', label: 'Key'}
          - {property: 'value', label: 'Value'}
      disabled_actions: ['new', 'delete']
