---
easy_admin:
  entities:
    DocumentTemplate:
      class: App\Domain\Entity\DocumentTemplate\DocumentTemplate
      label: 'Шаблоны документов CRM'
      list:
        actions: ['show']
        fields:
          - {property: 'name', label: 'Название в CRM'}
          - {property: 'year', label: 'Год', format: 'Y'}
          - {property: 'disciplinesName', label: 'Дисциплина'}
          - {property: 'documentType', label: 'Название для печати'}
      show:
        fields:
          - {property: 'id'}
          - {property: 'name', label: 'Название в CRM'}
          - {property: 'year', label: 'Год', format: 'Y'}
          - {property: 'disciplinesName', label: 'Дисциплина'}
          - {property: 'documentType', label: 'Название для печати'}
          - {property: 'updatedAt', label: 'Дата изменения'}
      disabled_actions: ['new', 'edit', 'delete']
