---
easy_admin:
  entities:
    Position:
      class: App\Domain\Entity\Position\Position
      label: 'Должности'
      list:
        actions: ['show']
        fields:
          - {property: 'id'}
          - {property: 'name', label: 'Название'}
      show:
        fields:
          - {property: 'id'}
          - {property: 'name', label: 'Название'}
          - {property: 'guid', label: 'GUID'}
      disabled_actions: ['new', 'edit', 'delete']
