---
easy_admin:
  entities:
    ReferenceInformation:
      class: App\Domain\Entity\ReferenceInformation\ReferenceInformation
      label: 'Нормативно-справочная информация'
      list:
        actions:
          - show
          - {name: 'edit', template: 'easy_admin_role_marketer.twig'}
          - {name: 'delete', template: 'easy_admin_role_marketer.twig'}
          - {name: 'new', label: 'Добавить запись', template: 'easy_admin_role_marketer.twig'}
        fields:
          - {property: 'id'}
          - {property: 'title', label: 'Название'}
          - {property: 'url', type: 'url', label: 'Ссылка'}
          - {property: 'active', label: 'Активность', role: 'ROLE_MARKETER'}
      show:
        actions:
          - {name: 'edit', template: 'easy_admin_role_marketer.twig'}
          - {name: 'delete', template: 'easy_admin_role_marketer.twig'}
      form:
        item_permission: 'ROLE_MARKETER'
        fields:
          - {property: 'title', label: 'Название', type_options: {empty_data: ''}}
          - {property: 'url', type: 'url', label: 'Ссылка', type_options: {empty_data: ''}}
          - {property: 'active', label: 'Активность'}
