---
easy_admin:
  entities:
    School:
      class: App\Domain\Entity\School\School
      label: 'Школы'
      list:
        item_permission: 'ROLE_MARKETER'
        actions:
          - show
        fields:
          - {property: 'id'}
          - {property: 'name', label: 'Название'}
      show:
        item_permission: 'ROLE_MARKETER'
        fields:
          - {property: 'id'}
          - {property: 'name', label: 'Название'}
      disabled_actions: ['new', 'delete', 'edit']
