---
easy_admin:
  entities:
    SiteOption:
      class: App\Domain\Entity\SiteOption
      label: 'Настройки Реестра'
      list:
        item_permission: 'ROLE_MARKETER'
        actions:
          - show
          - {name: 'edit', template: 'easy_admin_role_supervisor.twig'}
          - {name: 'delete', template: 'easy_admin_role_supervisor.twig'}
          - {name: 'new', label: 'Добавить запись', template: 'easy_admin_role_supervisor.twig'}
        fields:
          - {property: 'name', label: 'Название'}
          - {property: 'value', label: 'Значение'}
          - {property: 'description', label: 'Описание'}
          - {property: 'updatedAt', label: 'Дата последнего обновления'}
      show:
        actions:
          - {name: 'edit', template: 'easy_admin_role_supervisor.twig'}
          - {name: 'delete', template: 'easy_admin_role_supervisor.twig'}
      form:
        item_permission: ['ROLE_ADMIN', 'ROLE_SUPERVISOR']
        fields:
          - {property: 'name', label: 'Название', type_options: {empty_data: ''}}
          - {property: 'value', label: 'Значение'}
          - {property: 'description', label: 'Описание'}
