---
easy_admin:
  entities:
    Specialist:
      class: App\Domain\Entity\Specialist\Specialist
      controller: App\UI\Controller\EasyAdmin\AdminSpecialistController
      label: 'Специалисты'
      list:
        actions:
          - show
          - {name: 'edit', template: 'easy_admin_role_marketer.twig'}
          - {name: 'delete', template: 'easy_admin_role_supervisor.twig'}
        fields:
          - {property: 'id', label: 'BitrixID'}
          - {property: 'secondName', label: 'Фамилия'}
          - {property: 'firstName', label: 'Имя'}
          - {property: 'middleName', label: 'Отчество'}
          - {property: 'status', label: 'Статус', type: 'string'}
          - {property: 'company', label: 'Компания'}
          - {property: 'region', label: 'Регион'}
      show:
        fields:
          - {property: 'id', label: 'BitrixID'}
          - {property: 'secondName', label: 'Фамилия'}
          - {property: 'firstName', label: 'Имя'}
          - {property: 'middleName', label: 'Отчество'}
          - {property: 'statusName', label: 'Статус'}
          - {property: 'company', label: 'Компания'}
          - {property: 'region', label: 'Регион'}
          - {property: 'genderName', label: 'Пол'}
          - {property: 'dateOfBirth', label: 'Дата рождения', format: 'Y-m-d'}
          - {property: 'id2Position', label: 'Должность в id2'}
          - {property: 'position', label: 'Должность'}
          - {property: 'employmentType', label: 'Вид занятости'}
          - {property: 'schedule', label: 'Режим работы'}
          - {property: 'avatarUrl', label: 'Ссылка на аватар'}
        actions:
          - {name: 'updateDocuments', label: 'Обновить документы', css_class: 'btn'}
          - {name: 'edit', template: 'easy_admin_role_marketer.twig'}
          - {name: 'delete', template: 'easy_admin_role_supervisor.twig'}
          - {name: 'list'}
      edit:
        item_permission: 'ROLE_MARKETER'
        fields:
          - {property: 'id', label: 'BitrixID', type_options: {disabled: true}}
          - {property: 'secondName', label: 'Фамилия', type_options: {disabled: true}}
          - {property: 'firstName', label: 'Имя', type_options: {disabled: true}}
          - {property: 'middleName', label: 'Отчество', type_options: {disabled: true}}
          - {property: 'status', label: 'Статус', type: 'choice', type_options: {choices: {'Не в реестре': 0, 'Требуется аттестация': 1, 'Обучается': 2, 'Аттестованный': 3}, disabled: true}}
          - {property: 'company', label: 'Компания', type_options: {disabled: true}}
          - {property: 'region', label: 'Регион', type_options: {disabled: true}}
          - {property: 'gender', label: 'Пол', type: 'choice', type_options: {choices: {'Женский': 0, 'Мужской': 1}, disabled: true}}
          - {property: 'dateOfBirth', label: 'Дата рождения', type: 'App\UI\Form\Type\DateOfBirthType', type_options: {disabled: true}}
          - {property: 'id2Position', label: 'Должность в id2', type_options: {disabled: true}}
          - {property: 'position', label: 'Должность', type_options: {required: true}}
          - {property: 'employmentType', label: 'Вид занятости'}
          - {property: 'schedule', label: 'Режим работы'}
          - {property: 'avatar', label: 'Ссылка на аватар', type: 'App\UI\Form\Type\ImageUrlType', type_options: {disabled: true}}
        actions:
          - {name: 'delete', template: 'easy_admin_role_supervisor.twig'}
          - {name: 'list'}
      disabled_actions: ['new']
