---
easy_admin:
  entities:
    User:
      class: App\Domain\Entity\User
      label: 'Пользователи'
      list:
        item_permission: 'ROLE_MARKETER'
        actions:
          - show
          - {name: 'edit', template: 'easy_admin_role_supervisor.twig'}
        fields:
          - {property: 'id'}
          - {property: 'name', label: 'Имя'}
          - {property: 'role', label: 'Роль'}
          - {property: 'email', label: 'Email'}
          - {property: 'createdAt', label: 'Дата создания'}
          - {property: 'isActive', label: 'Статус активности', role: ['ROLE_ADMIN', 'ROLE_SUPERVISOR']}
      show:
        item_permission: 'ROLE_MARKETER'
        actions:
          - {name: 'edit', template: 'easy_admin_role_supervisor.twig'}
        fields:
          - {property: 'id'}
          - {property: 'name', label: 'Имя'}
          - {property: 'role', label: 'Роль'}
          - {property: 'email', label: 'Email'}
          - {property: 'createdAt', label: 'Дата создания'}
          - {property: 'isActive', label: 'Статус активности'}
      edit:
        item_permission: ['ROLE_ADMIN', 'ROLE_SUPERVISOR']
        fields:
          - {property: 'id', type_options: {disabled: true}}
          - {property: 'name', label: 'Имя', type_options: {disabled: true}}
          - {property: 'email', label: 'Email', type_options: {disabled: true}}
          - {property: 'createdAt', label: 'Дата создания', type_options: {disabled: true}}
          - {property: 'roleRealName', permission: ROLE_SUPERVISOR, label: 'Роль', type: 'choice', type_options: {choices: {'Гость': ROLE_GUEST, 'Редактор': ROLE_MARKETER, 'Руководитель': ROLE_SUPERVISOR, 'Администратор': ROLE_ADMIN}, required: true}}
          - {property: 'roleRealNameByAdmin', permission: ROLE_ADMIN, label: 'Роль', type: 'choice', type_options: {choices: {'Гость': ROLE_GUEST, 'Редактор': ROLE_MARKETER, 'Руководитель': ROLE_SUPERVISOR, 'Администратор': ROLE_ADMIN}, required: true}}
          - {property: 'isActive', label: 'Статус активности'}
      disabled_actions: ['new', 'delete']
