---
App\Domain\Entity\AttestationCommissionMember\AttestationCommissionMember:
  type: entity
  table: attestation_commission_member
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    firstName:
      type: string
      options:
        comment: 'Имя'
    secondName:
      type: string
      options:
        comment: 'Фамилия'
    middleName:
      type: string
      nullable: true
      options:
        comment: 'Отчество'
    imageUrl:
      type: string
      nullable: true
      options:
        comment: 'Ссылка на аватар'
    description:
      type: string
      options:
        comment: 'Описание должности'
    isLeader:
      type: boolean
      options:
        comment: 'Признак председателя комиссии'
    active:
      type: boolean
      options:
        comment: 'Активность'
        default: true
    updatedAt:
      type: datetime_immutable
      nullable: true
      options:
        comment: 'Дата последнего изменения'
