---
App\Domain\Entity\Position\Position:
  type: entity
  table: positions
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      options:
        comment: 'Должность'
    guid:
      type: string
      unique: true
      options:
        comment: 'GUID'
