---
App\Domain\Entity\Product\Product:
  type: entity
  table: product
  id:
    id:
      type: integer
      generator:
        strategy: NONE
  fields:
    name:
      type: text
      options:
        comment: 'Название'
