---
App\Domain\Entity\Region\Region:
  type: entity
  table: region
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      options:
        comment: 'Название'
