---
App\Domain\Entity\RegulatoryDocuments\RegulatoryDocuments:
  type: entity
  table: regulatory_documents
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    url:
      type: string
      nullable: true
      options:
        comment: 'Ссылка'
    title:
      type: string
      options:
        comment: 'Название'
    active:
      type: boolean
      options:
        comment: 'Активность'
        default: true
    updatedAt:
      type: datetime_immutable
      nullable: true
      options:
        comment: 'Дата изменения'
