---
App\Domain\Entity\SiteOption:
  type: entity
  table: site_option
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      unique: true
    value:
      type: text
      nullable: true
    description:
      type: text
      nullable: true
    createdAt:
      type: datetime_immutable
    updatedAt:
      type: datetime_immutable
      nullable: true
