---
App\Domain\Entity\Skill\Skill:
  type: entity
  table: skill
  id:
    internalId:
      type: integer
      generator:
        strategy: AUTO
  fields:
    id:
      type: string
      nullable: false
    name:
      type: string
      nullable: false
    updatedAt:
      type: datetime_immutable
      nullable: true
    macroSkillId:
      type: string
      nullable: true
    macroSkillName:
      type: string
      nullable: true
    macroTypeId:
      type: string
      nullable: true
    macroTypeName:
      type: string
      nullable: true
    reestrId:
      type: string
      nullable: true
    reestrName:
      type: string
      nullable: true
    macroWeight:
      type: integer
      nullable: false
    weight:
      type: integer
      nullable: false
    active:
      type: boolean
      nullable: false
      options:
        comment: 'Флаг активности'
        default: true
