---
App\Domain\Entity\SpecialistWorkSchedule\SpecialistWorkSchedule:
  type: entity
  table: specialist_work_schedule
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      options:
        comment: 'Название'
