---
App\Domain\Entity\Specialist\SpecialistOccupationType:
  type: entity
  table: specialist_occupation_type
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      options:
        comment: 'Название'
