---
sentry:
    options:
        environment: '%kernel.environment%'
        release: '%env(GIT_COMMIT_SHA)%'
        excluded_exceptions:
            - App\Application\Exception\ValidationException
            - Symfony\Component\HttpKernel\Exception\HttpException
            - Symfony\Component\Security\Core\Exception\AccessDeniedException
            - App\Domain\Repository\NotFoundException
    dsn: '%env(SENTRY_DSN)%'
