---
# Expose your documentation as JSON swagger compliant
app.swagger:
    path: /_/swagger
    methods: GET
    defaults: {_controller: nelmio_api_doc.controller.swagger}

app.swagger_ui:
    path: /_/swaggerui
    methods: GET
    defaults: {_controller: nelmio_api_doc.controller.swagger_ui}
