---
sentry:
  options:
    environment: '%kernel.environment%'
    release: '%env(GIT_COMMIT_SHA)%'
    excluded_exceptions:
      - DomainException
      - App\Application\Exception\ValidationException
      - App\Domain\Repository\NotFoundException
      - Symfony\Component\HttpKernel\Exception\HttpException
      - Symfony\Component\Security\Core\Exception\AccessDeniedException
    tags:
      x-host: '%env(X_HOST)%'
      cli: '%env(CLI)%'
  dsn: '%env(SENTRY_DSN)%'
