---
fm_elfinder:
  instances:
    default:
      connector:
        roots:
          images:
            driver: Flysystem
            path: ''
            url: ''
            tmb_url: 'self'
            flysystem:
              type: aws_s3_v3
              options:
                aws_s3_v3:
                  version: 'latest'
                  endpoint: '%env(AWS_S3_ENDPOINT)%'
                  key: '%env(AWS_S3_KEY)%'
                  secret: '%env(AWS_S3_SECRET)%'
                  region: '%env(AWS_S3_REGION)%'
                  bucket_name: '%env(AWS_S3_BUCKET)%'
            upload_allow: ['all']
