---
framework:
  secret: '%env(APP_SECRET)%'
  session:
    handler_id: snc_redis.session.handler
  csrf_protection: false
  php_errors:
    log: true

  cache:
    app: cache.adapter.redis
    default_redis_provider: snc_redis.default
    pools:
      doctrine.result_cache_pool:
        adapter: cache.app
        default_lifetime: 25200
      doctrine.system_cache_pool:
        adapter: cache.system

  validation: {enable_annotations: true}

  assets:
    base_path: 'assets'
