---
security:
    providers:
        app_user_provider:
            entity:
                class: App\Domain\Entity\User
                property: uuid
    firewalls:
        main:
            pattern: ^/
            anonymous: ~
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 86400
                path: /
                always_remember_me: true
            logout:
                path: /admin/logout
                target: /admin/login
            guard:
                authenticators:
                    - App\Application\Auth\Oauth
    role_hierarchy:
        ROLE_ADMIN: [ROLE_MARKETER, ROLE_GUEST]
        ROLE_SUPERVISOR: [ROLE_MARKETER, ROLE_GUEST]
        ROLE_MARKETER: [ROLE_GUEST]
    access_control:
        - {path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/admin, roles: ROLE_GUEST}
        - {path: ^/admin/file-manager, roles: ROLE_MARKETER}
        - {path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
