---
vich_uploader:
    db_driver: orm
    storage: flysystem
    mappings:
        document_type_preview:
            upload_destination: s3.storage
            inject_on_load: true
            uri_prefix: ''
            namer: 'App\Infrastructure\VichUploaderNamer\DocumentTypePreviewNamer'
        document_type_background:
            upload_destination: s3.storage
            inject_on_load: true
            uri_prefix: ''
            namer: 'App\Infrastructure\VichUploaderNamer\DocumentTypeBackgroundNamer'
        attestation_commission_member_avatar:
            upload_destination: s3.storage
            inject_on_load: true
            uri_prefix: ''
            namer: 'App\Infrastructure\VichUploaderNamer\AttestationCommissionMemberAvatarNamer'
        regulatory_documents_file:
            upload_destination: s3.storage
            inject_on_load: true
            uri_prefix: ''
            namer: 'App\Infrastructure\VichUploaderNamer\RegulatoryDocumentsFileNamer'
