---

# Common
.datafix:
  when: manual
  except:
  only:
    - /^datafix/
  variables:
    DEPLOY_DB_MIGRATION_COMMAND: 'php /var/www/bin/console app:datafix:execute --x-host=${X_HOST} ${DATAFIX_CLASS_NAME}'
    DEPLOY_CHECK_DEPLOYMENT_STATUS_TIMEOUT: 36000

# DEV
.datafix-dev:
  timeout: 600min
  extends:
    - db-migration-dev
    - .datafix

# RC
.datafix-rc:
  timeout: 600min
  extends:
    - db-migration-rc
    - .datafix

# PROD
.datafix-prod:
  timeout: 600min
  dependencies:
    - build
  extends:
    - db-migration-prod
    - .datafix
